### ISSUE TITLE
"ENOSPC: no space left on device " even though I have 2tb space free

### ISSUE THREAD

**Issue by 5honk** [2anki/2anki.net#1348] opened 2023-11-18 13:18 UTC
I have tried to convert my notion toggles into Anki flashcards, until I came across an error "ENOSPC: no space left on device" on Mac. I have also tried converting the same notion on windows and still I come across the same problem.

I used previously converted zip files to convert into Anki flash cards yet the problem remains the same. :(

**Comment by aalemayhu** [comment] 2023-11-18 14:40
Duplicate of #1346

**Closed by aalemayhu** 2023-11-18 14:40 UTC
