### ISSUE TITLE
Self-hosting. Cannot upload neither download .zip files.

### ISSUE THREAD

**Issue by AugustoHuerta** [2anki/2anki.net#1391] opened 2024-01-07 16:40 UTC
**Describe the bug**
I am trying to use desktop docker with Notion2Anki but cannot upload my .zip files in the Upload page.
What message it gives me?: "The "path" argument must be of type string. Received undefined"

**To Reproduce**
Steps to reproduce:
1. Build the container.
2. Run it with the following command: `docker run -p 8080:8080 --detach --name nn`
3. Go to the upload page and try to ankize a notion page.
4. Fail.

**Expected behavior**
Not fail, getting my ankicards like I can get in the oficial server.

**Screenshots**
![image](https://github.com/2anki/2anki.net/assets/88601281/8fa05d41-af94-450d-a901-d3c5242db707)

**Desktop (please complete the following information):**
- Docker desktop. v4.26.1 default version.
- Windows 10 (Host) & WSL 2 Ubuntu 22.04.2 LTS (Docker containers)
- Notion2Anki commit [95892e5](https://github.com/2anki/2anki.net/tree/95892e51becf106b7ab98da4d0b4db1f97fd5747) with the [Docker file ](https://github.com/2anki/2anki.net/blob/92e4c04a09df688f42dae8cd984e72a1a3594a35/Dockerfile) from the commit [f0a1256](https://github.com/2anki/2anki.net/commit/f0a125620f961d2ca9275a69c4499a5f98639732)
- Browser: Brave

**Additional context**
Really grateful for all the support all people give to this project and hope this isn't happening to only me. Kudos for y'all.
I am not really an expert in javascript, neither Typescript or Docker but I have a question @aalemayhu: Why did you remove the docker image in recent commits?

**Comment by aalemayhu** [comment] 2024-01-07 16:55
The long-term plan is to provide documentation for self-hosting and running it locally. This is a duplicate of https://github.com/2anki/2anki.net/issues/552 

I'm closing this issue, but I wanted to clarify why the Dockerfile was removed. I migrated the server from DigitalOcean, where it was running in a container with Dokku, to bare metal. Since the project is no longer using Docker, I removed the Dockerfile to avoid any confusion or maintenance issues. I didn't have the time to continue supporting Docker for this project.

**Closed by aalemayhu** 2024-01-07 16:55 UTC
